use_frameworks!

platform :ios, '9.0'

target 'MKTrackerPlusSDK_Example' do
  pod 'MKTrackerPlusSDK', :path => '../'

  target 'MKTrackerPlusSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
