post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
platform :ios,'12.0'

inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'MKTrackerPlusSDK_Example' do
  pod 'MKTrackerPlusSDK', :path => '../'
  
  pod 'mokoLibrary'
  pod 'YYKit'
  pod 'MKBLEBaseModule'
  pod 'MLInputDodger'
  pod 'iOSDFULibrary','4.6.1'
  pod 'FMDB'

  target 'MKTrackerPlusSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
